name: Pylint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        $pylint_output = pylint $(git ls-files '*.py')
        Write-Output "$pylint_output"
        $regex_pattern = "rated at (\d+\.\d+)\/10\.00"
        $match = [regex]::Match($pylint_output, $regex_pattern)
        if ($match.Success) {
          $pylint_score = $match.Groups[1].Value
          Write-Output "Pylint score was $pylint_score"
          if ([decimal]$pylint_score -lt 9.00) {
            Write-Output "Pylint score less than 9, failing the build"
            exit 1
          }
        } else {
          Write-Output "Pylint score not found"
          exit 1
        }
      shell: pwsh
